name: Production Build

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
env:
    TAG: ${{ secrets.DOCKER_HUB_USER }}/ddia-web:latest
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Create .env file
          run: |
            echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
            echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> .env
            echo "FORMS_TOKEN=${{ secrets.API_TOKEN }}" >> .env
            echo "REVALIDATION_TOKEN=${{ secrets.REVALIDATION_TOKEN }}" >> .env
            echo "SITE_HOST=${{ secrets.SITE_HOST }}" >> .env
            echo "I18NEXUS_API_KEY=${{ secrets.I18NEXUS_API_KEY }}" >> .env
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USER }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
        - uses: docker/build-push-action@v4
          with:
            context: .
            tags: ${{ env.TAG }}
            push: true
            platforms: linux/amd64
            cache-from: type=registry,ref=${{ env.TAG }}
            cache-to: type=inline
